# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dfs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\x12\x03\x64\x66s\">\n\x0fRegisterRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"J\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nfree_bytes\x18\x02 \x01(\x03\x12\x11\n\tblock_ids\x18\x03 \x03(\t\"\x1f\n\x11HeartbeatResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x86\x01\n\x0fNameNodeService\x12\x37\n\x08Register\x12\x14.dfs.RegisterRequest\x1a\x15.dfs.RegisterResponse\x12:\n\tHeartbeat\x12\x15.dfs.HeartbeatRequest\x1a\x16.dfs.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=18
  _globals['_REGISTERREQUEST']._serialized_end=80
  _globals['_REGISTERRESPONSE']._serialized_start=82
  _globals['_REGISTERRESPONSE']._serialized_end=117
  _globals['_HEARTBEATREQUEST']._serialized_start=119
  _globals['_HEARTBEATREQUEST']._serialized_end=193
  _globals['_HEARTBEATRESPONSE']._serialized_start=195
  _globals['_HEARTBEATRESPONSE']._serialized_end=226
  _globals['_NAMENODESERVICE']._serialized_start=229
  _globals['_NAMENODESERVICE']._serialized_end=363
# @@protoc_insertion_point(module_scope)
